### ISSUE TITLE
Error while fetching the package

### ISSUE THREAD

**Issue by fdidron** [mattn/go-libvterm#4]
Hello,

I'm trying to use this package that would be super helpful for a project I'm working on.

When trying to go get the package, I'm getting the following error:

```
dev/go/src/github.com/mattn/go-libvterm/vterm-pkgconfig.go:16:22: sc.cell.fg.red undefined (type _Ctype_VTermColor has no field or method red)
dev/go/src/github.com/mattn/go-libvterm/vterm-pkgconfig.go:17:22: sc.cell.fg.green undefined (type _Ctype_VTermColor has no field or method green)
dev/go/src/github.com/mattn/go-libvterm/vterm-pkgconfig.go:18:22: sc.cell.fg.blue undefined (type _Ctype_VTermColor has no field or method blue)
dev/go/src/github.com/mattn/go-libvterm/vterm-pkgconfig.go:25:22: sc.cell.bg.red undefined (type _Ctype_VTermColor has no field or method red)
dev/go/src/github.com/mattn/go-libvterm/vterm-pkgconfig.go:26:22: sc.cell.bg.green undefined (type _Ctype_VTermColor has no field or method green)
dev/go/src/github.com/mattn/go-libvterm/vterm-pkgconfig.go:27:22: sc.cell.bg.blue undefined (type _Ctype_VTermColor has no field or method blue)
dev/go/src/github.com/mattn/go-libvterm/vterm-pkgconfig.go:37:32: cannot use _Ctype_uchar(col.R) (type _Ctype_uchar) as type byte in array literal
dev/go/src/github.com/mattn/go-libvterm/vterm-pkgconfig.go:37:50: cannot use _Ctype_uchar(col.G) (type _Ctype_uchar) as type byte in array literal
dev/go/src/github.com/mattn/go-libvterm/vterm-pkgconfig.go:37:68: cannot use _Ctype_uchar(col.B) (type _Ctype_uchar) as type byte in array literal
```

I tried on both OS X and Ubuntu, with Golang version 1.17.2

I'm happy to spend time on fixing this and provide a PR, but before I was wondering if you had any pointers.

**Comment by fdidron** [comment]
Oh I forgot to add, I do have libvterm installed and available via pkg-config

**Comment by mattn** [comment]
So closable?

**Comment by fdidron** [comment]
@mattn I will close for now and look for a fix, propose a PR if I find one. If you have any idea / pointers to what would cause the issue let me know.

**Comment by ushitora-anqou** [comment]
@fdidron This issue may be outdated for you, but I'll leave some comments here because I ran into the same error and found some workaround for it. Build this package with `vterm-libterm.go`, rather than `vterm-pkgconfig.go`. This can be done either by enabling the `libvterm` build constraint, or simply by removing `vterm-pkgconfig.go` and updating `vterm-libterm.go`, like [mine](https://github.com/ushitora-anqou/go-libvterm/commit/aaaf2bfefc60a39f218cbe04bd4ae00b0a71de37).

Note that the main problem of this issue is that recent Ubuntu (at least Ubuntu 20.04 LTS, which I'm using) provides newer versions of libvterm, and their C interfaces are different from the old ones, which has been already pointed out by #3.

Hope this helps!

**Comment by mattn** [comment]
You can build with `go build -tags libvterm`.

**Comment by fdidron** [comment]
@ushitora-anqou Thanks, using the `libvterm` tag did the trick

**Comment by mattn** [comment]
Ah, I notice the libvterm had breaking changes. Addressing in https://github.com/mattn/go-libvterm/pull/5
